cognito_username = 'lucian@example.com'
cognito_password = 'somepassword12345'
cognito_userpool_id = 'eu-west-1_1stJ3rJrI'
cognito_region = 'eu-west-1'
app_client_id = '5jgb4ulgu3cgfotqedt6eh8r6l'
app_client_secret = ''
